---

- name: Create interfaces
  hosts: all_routers

  tasks:      
    - name: Create interfaces
      cisco.ios.ios_config:
        src: templates/interfaces.j2
        
    - name: enable interfaces
      cisco.ios.ios_config:
        parents: "interface Ethernet{{ item.0 }}"
        lines: "no shutdown"
      with_items:
        - "{{ interfaces.items() }}"

- name: Create bgp
  hosts: all_routers

  tasks:      
    - name: Create bgp
      cisco.ios.ios_config:
        src: templates/bgp.j2

- name: Create vlans
  hosts: all_switches

  tasks:      
    - name: Create vlans
      cisco.ios.ios_config:
        src: templates/vlans.j2

- name: Create LAGP
  hosts: mscw_switches

  tasks:      
    - name: Set link aggregation group to members
      cisco.ios.ios_lag_interfaces:
        config:
        - name: Port-channel1
          members:
          - member: Ethernet0/1
            mode: active
          - member: Ethernet0/2
            mode: active
        state: merged
        
- name: Crypto
  hosts: hubs:spokes
  
  tasks:
    - name: Deploy crypto config
      cisco.ios.ios_config:
        src: crypto.j2  

- name: Hubs settings
  hosts: hubs

  tasks:      
    - name: Hubs settings
      cisco.ios.ios_config:
        src: templates/hubs.j2
        
- name: Spokes settings
  hosts: spokes

  tasks:      
    - name: Spokes settings
      cisco.ios.ios_config:
        src: templates/spokes.j2
      
- name: Route for spokes
  hosts: spokes

  tasks:      
    - name: route for spokes
      cisco.ios.ios_config:
        src: templates/route_for_spokes.j2 
        
#- name: Write memory
#  hosts: all_devices
#
#  tasks:
#    - name: Write memory
#      cisco.ios.ios_command:
#        commands: "write memory"
