---

- name: Create interfaces
  hosts: all_devices

  tasks:      
    - name: Create interfaces
      cisco.ios.ios_config:
        src: templates/interfaces.j2
      
    - name: enable interfaces
      cisco.ios.ios_config:
        parents: "interface Ethernet{{ item.0 }}"
        lines: "no shutdown"
      with_items:
        - "{{ interfaces.items() }}"

- name: Create bgp
  hosts: all_devices

  tasks:      
    - name: Create bgp
      cisco.ios.ios_config:
        src: templates/bgp.j2

- name: Write memory
  hosts: all_devices

  tasks:
    - name: Write memory
      cisco.ios.ios_command:
        commands: "write memory"
