---

config:
  vlans:
    vlan:
      - name: "USERS"
        vlan_id: "200"
  interfaces:
    access:
      - name: Ethernet0/3
        alias: "USERS"
        interface_mode: access
        vlan:
          members: "200"
    trunk:
      - name: Ethernet1/0
        alias: "TO_DC2"
        interface_mode: trunk
        allowed_vlans:
          members: 200
      - name: Port-channel1
        interface_mode: trunk
        allowed_vlans:
         members: 100,200
