---

config:
  vlans:
    vlan:
      - name: "USERS"
        vlan_id: "20"
  interfaces:
    access:
      - name: Ethernet0/2
        alias: "USERS"
        interface_mode: access
        vlan:
          members: "20"
    trunk:
      - name: Ethernet0/1
        alias: "TO_SOCHI-R"
        interface_mode: trunk
        allowed_vlans:
          members: 20
